name: FL-Visualization Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        cd code
        pip install -r requirements.txt
        
    - name: Run automated tests
      run: |
        cd code
        python test.py all
        
    - name: Run quick validation
      run: |
        cd code
        python test.py quick
        
    - name: Generate test coverage report
      run: |
        cd code
        python test.py coverage > test_report.txt
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: code/test_report.txt
